package io.aurigraph.v11.auth;

import jakarta.ws.rs.*;
import jakarta.ws.rs.core.MediaType;
import jakarta.ws.rs.core.Response;
import jakarta.ws.rs.core.Context;
import jakarta.ws.rs.core.HttpHeaders;
import jakarta.inject.Inject;
import io.aurigraph.v11.user.User;
import io.aurigraph.v11.session.SessionService;
import org.jboss.logging.Logger;
import io.quarkus.elytron.security.common.BcryptUtil;

import java.time.LocalDateTime;
import java.util.*;

@Path("/api/v11/login")
@Produces(MediaType.APPLICATION_JSON)
@Consumes(MediaType.APPLICATION_JSON)
public class LoginResource {
    private static final Logger LOG = Logger.getLogger(LoginResource.class);

    @Inject
    SessionService sessionService;

    @Inject
    AuthTokenService authTokenService;

    @POST
    @Path("/authenticate")
    public Response authenticate(LoginRequest request, @Context HttpHeaders httpHeaders) {
        try {
            // Validate input
            if (request.getUsername() == null || request.getUsername().isBlank() ||
                request.getPassword() == null || request.getPassword().isBlank()) {
                return Response.status(Response.Status.BAD_REQUEST)
                    .entity(new ErrorResponse("Username and password are required"))
                    .build();
            }

            LOG.debugf("Login attempt for username: %s", request.getUsername());

            // Query user from database using Panache
            User user = User.findByUsername(request.getUsername());
            if (user == null) {
                LOG.warnf("Login failed: User not found - %s", request.getUsername());
                LOG.debugf("Available users in database:");
                long totalUsers = User.count();
                LOG.debugf("Total users in database: %d", totalUsers);
                return Response.status(Response.Status.UNAUTHORIZED)
                    .entity(new ErrorResponse("Invalid credentials"))
                    .build();
            }

            LOG.debugf("User found: %s (email: %s, hash: %s)", user.username, user.email,
                user.passwordHash != null ? user.passwordHash.substring(0, Math.min(20, user.passwordHash.length())) + "..." : "NULL");

            // Verify password using BCrypt
            boolean passwordMatches = BcryptUtil.matches(request.getPassword(), user.passwordHash);
            LOG.debugf("Password match result: %b", passwordMatches);

            if (!passwordMatches) {
                LOG.warnf("Login failed: Invalid password for user - %s", request.getUsername());
                return Response.status(Response.Status.UNAUTHORIZED)
                    .entity(new ErrorResponse("Invalid credentials"))
                    .build();
            }

            // Create session
            Map<String, Object> userData = new HashMap<>();
            userData.put("userId", user.id);
            userData.put("email", user.email);
            userData.put("role", user.role != null ? user.role.name : "USER");

            String sessionId = sessionService.createSession(request.getUsername(), userData);

            // Store JWT token in database
            try {
                String clientIp = "127.0.0.1"; // In production, extract from request headers
                String userAgent = httpHeaders.getHeaderString("User-Agent");

                // Generate a token (in production, this would be generated by JwtService)
                String token = generateAccessToken(user.id.toString(), user.email);
                LocalDateTime expiresAt = LocalDateTime.now().plusHours(24);

                // Store token in database
                authTokenService.storeToken(
                    user.id.toString(),
                    user.email,
                    token,
                    AuthToken.TokenType.ACCESS,
                    expiresAt,
                    clientIp,
                    userAgent != null ? userAgent : "Unknown"
                );

                LOG.infof("✅ JWT token stored for user %s from IP %s", user.email, clientIp);

                // Also store refresh token if needed
                String refreshToken = generateRefreshToken(user.id.toString(), user.email);
                LocalDateTime refreshExpiresAt = LocalDateTime.now().plusDays(7);

                authTokenService.storeToken(
                    user.id.toString(),
                    user.email,
                    refreshToken,
                    AuthToken.TokenType.REFRESH,
                    refreshExpiresAt,
                    clientIp,
                    userAgent != null ? userAgent : "Unknown"
                );

                LOG.infof("✅ Refresh token stored for user %s", user.email);

            } catch (Exception tokenError) {
                LOG.warnf(tokenError, "Failed to store tokens for user %s, continuing without token storage", user.email);
            }

            LOG.infof("Login successful: %s (Session: %s)", request.getUsername(), sessionId);

            // Return response with session cookie and JWT tokens
            LoginResponse response = new LoginResponse(
                sessionId,
                request.getUsername(),
                true,
                "Login successful"
            );

            return Response.ok(response)
                .header("Set-Cookie", "session_id=" + sessionId + "; Path=/; HttpOnly; Max-Age=28800")
                .build();

        } catch (Exception e) {
            LOG.errorf(e, "Login error for user %s", request.getUsername());
            return Response.status(Response.Status.INTERNAL_SERVER_ERROR)
                .entity(new ErrorResponse("Login failed: " + e.getMessage()))
                .build();
        }
    }

    /**
     * Generate a simple access token
     * In production, this should be delegated to JwtService
     */
    private String generateAccessToken(String userId, String email) {
        // This is a placeholder - in production, use proper JWT generation
        return "access_" + UUID.randomUUID().toString();
    }

    /**
     * Generate a simple refresh token
     * In production, this should be delegated to JwtService
     */
    private String generateRefreshToken(String userId, String email) {
        // This is a placeholder - in production, use proper JWT generation
        return "refresh_" + UUID.randomUUID().toString();
    }

    @GET
    @Path("/verify")
    public Response verifySession(@CookieParam("session_id") String sessionId) {
        if (sessionId == null) {
            return Response.status(Response.Status.UNAUTHORIZED)
                .entity(new ErrorResponse("No session"))
                .build();
        }

        SessionService.SessionData session = sessionService.getSession(sessionId);
        if (session == null) {
            return Response.status(Response.Status.UNAUTHORIZED)
                .entity(new ErrorResponse("Invalid or expired session"))
                .build();
        }

        return Response.ok(new SessionResponse(
            sessionId,
            session.getUsername(),
            session.getUserData()
        )).build();
    }

    @POST
    @Path("/logout")
    public Response logout(@CookieParam("session_id") String sessionId) {
        try {
            if (sessionId != null) {
                SessionService.SessionData session = sessionService.getSession(sessionId);
                if (session != null) {
                    String username = session.getUsername();
                    Map<String, Object> userData = session.getUserData();

                    // Revoke all tokens for the user
                    if (userData != null && userData.containsKey("userId")) {
                        String userId = userData.get("userId").toString();
                        try {
                            int revokedCount = authTokenService.revokeAllTokensForUser(userId, "User logout");
                            LOG.infof("✅ Revoked %d tokens for user %s on logout", revokedCount, username);
                        } catch (Exception tokenError) {
                            LOG.warnf(tokenError, "Failed to revoke tokens for user %s", username);
                        }
                    }
                }
                sessionService.invalidateSession(sessionId);
            }
            return Response.ok(new SuccessResponse("Logged out successfully"))
                .header("Set-Cookie", "session_id=; Path=/; Max-Age=0")
                .build();
        } catch (Exception e) {
            LOG.errorf(e, "Logout error");
            return Response.status(Response.Status.INTERNAL_SERVER_ERROR)
                .entity(new ErrorResponse("Logout failed: " + e.getMessage()))
                .build();
        }
    }

    // DTOs
    public static class LoginRequest {
        private String username;
        private String password;

        public LoginRequest() {}

        public LoginRequest(String username, String password) {
            this.username = username;
            this.password = password;
        }

        public String getUsername() { return username; }
        public void setUsername(String username) { this.username = username; }
        public String getPassword() { return password; }
        public void setPassword(String password) { this.password = password; }
    }

    public static class LoginResponse {
        private String sessionId;
        private String username;
        private boolean success;
        private String message;

        public LoginResponse(String sessionId, String username, boolean success, String message) {
            this.sessionId = sessionId;
            this.username = username;
            this.success = success;
            this.message = message;
        }

        public String getSessionId() { return sessionId; }
        public String getUsername() { return username; }
        public boolean isSuccess() { return success; }
        public String getMessage() { return message; }
    }

    public static class SessionResponse {
        private String sessionId;
        private String username;
        private Map<String, Object> userData;

        public SessionResponse(String sessionId, String username, Map<String, Object> userData) {
            this.sessionId = sessionId;
            this.username = username;
            this.userData = userData;
        }

        public String getSessionId() { return sessionId; }
        public String getUsername() { return username; }
        public Map<String, Object> getUserData() { return userData; }
    }

    public static class ErrorResponse {
        private String error;

        public ErrorResponse(String error) {
            this.error = error;
        }

        public String getError() { return error; }
    }

    public static class SuccessResponse {
        private String message;

        public SuccessResponse(String message) {
            this.message = message;
        }

        public String getMessage() { return message; }
    }
}
